### ISSUE TITLE
Write tests for the procedure of adding a new transaction

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator#93]

**Comment by FredrikAugust** [comment]
On it.

**Comment by FredrikAugust** [comment]
Turns out I can't really do it as I want to. The way this _should_ be tested, is to render the `AddTransaction` component, fill it out, and submit it. For this though, you need to log in after rendering the component. This is an `async` action, which naturally will cause a ripple effect in the `AddTransaction` component, because the newly updated `AuthState` will cause a rerender.

And according to the react docs, when you want to perform an action that will affect the DOM, you need to use the `act(() => { ... })` function. This however - as of now, does not support `async` actions. 

This means that it is currently not feasible to test this, and I suggest we just roll with a separate back- and frontend test. The frontend should test that the submit function is called on click - with the correct parameters, and the backend test should test that the transaction is created when submitted.

`async` `act` will however be supported with the release of React `16.9.0`, so we will be able to test it when that releases.

**Comment by NicolajNiels1** [comment]
What I would like to be tested is that:
- Unsuccessful form validation (in frontend) renders error messages by appropriate input fields.
- Some basic accessibility features, e.g. labels exists

**Comment by FredrikAugust** [comment]
Closing as it is a stale issue, and the procedure is thoroughly tested.
